version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-book-don-ex-system
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SEUSL
      MYSQL_DATABASE: book_don_ex_system
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - mysql_data:/var/lib/mysql

#volumes:
#  mysql_data:
  compiler:
    build: .
    image: ubuntu-gcc:latest
    container_name: ubuntu-gcc
    restart: unless-stopped
    volumes: 
    - ./:/Book_system
    network_mode: "host"
    working_dir: /Book_system
    command: sh -c "cd /Book_system && gcc main.c database.c user_management.c user.c admin.c -o book_system -lmysqlclient && tail -f /dev/null"
